version: '2'

services:

    db:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=12345
        restart: always

    smlr:
        image: alexz2/smaller
        restart: always
        links:
            - db
        ports:
            - "80:80"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=12345
            - SMLR.PREFIX=http://localhost:80/
            - SERVER_PORT=80
